### ISSUE TITLE
Feature request: split() and findall() functions

### ISSUE THREAD

**Issue by mr-c** [grtetrault/pcre2.py#1]
Hellos and thank you for this library!

I'm trying to migrate some code from https://github.com/awahlig/python-pcre/ and I'm missing two functions:

1.  `split()`
     https://github.com/awahlig/python-pcre/blob/21cc038ade8eb6154c6dd21da26dbd49b9eb3bae/python/pcre.py#L166
     → https://github.com/awahlig/python-pcre/blob/21cc038ade8eb6154c6dd21da26dbd49b9eb3bae/python/pcre.py#L46
2. `findall()`
    https://github.com/awahlig/python-pcre/blob/21cc038ade8eb6154c6dd21da26dbd49b9eb3bae/python/pcre.py#L169
    → https://github.com/awahlig/python-pcre/blob/21cc038ade8eb6154c6dd21da26dbd49b9eb3bae/python/pcre.py#L61

I have a workaround for `findall()` and I'm about to try to implement my own `split()` using your library, but it would be probably faster for someone more familiar than I am :-)

**Comment by mr-c** [comment]
Here are my implementations of `groups()`, `split()`, and `findall()`: https://salsa.debian.org/crusoe/debmutate/-/commit/d55d327c2dd5dd9d225bff665b56959ca9019b59#7f20fe78c03d40414ff9b6802de566566eb71a02_60_60

Do you want me to send a PR?

**Comment by grtetrault** [comment]
Thanks for the interest here! I think this is good functionality to add, and your implementation looks in line with python's `re` lib. Happy to review a PR on this - I can also make these changes on my end (though it may be a few days)

Some thoughts if you're sending a PR - the best spot for `split` and `findall` would be in `methods.pyx` which has some convenience functions already. `groups` could be added as a class method of `Match` to stay close to the `re` API. Also, I think this would warrant a new test file for methods on top of the base
